### ISSUE TITLE
Result difference from the original 2006 RMP paper

### ISSUE THREAD

**Issue by styojm** [WUST-FOG/gnlse-python#6]
Hi Sylwia and the team. 
  Thank you very much for coming up with this python code for GNLSE simulation. I tried the code and it worked perfectly! 
  Just one thing that's bothering me now --- by running the code with the same parameters as in the 2006 Dudley paper, I noticed some differences in the result. One major difference as you could see from the comparison picture below: the red-shifted component in the original paper was well below 1200nm whereas the simulation code gave me somewhere ~1200nm; Also in the temporal domain, the last soliton was delayed more (~3.5 ps) as compared to what's in the paper (probably ~2.5 ps).
![SC comparison](https://user-images.githubusercontent.com/49457559/127078368-344fc274-9e1c-443a-a9d7-70d09905dbea.png)
  I don't have MATLAB available, so I'm not sure if this was the issue in the original MATLAB code (https://github.com/jtravs/SCGBookCode) or it's due to some intrinsic difference between MATLAB and scipy on how they solve the ODE? If you could comment or suggest a solution that would be great.

Thanks again for the great work.
 - Yujie Shen

**Comment by majsylw** [comment]
Hi Yujie Shen,
we are very glad that you found our code easy to run and useful.
But to reply to your question, the mentioned difference is not exacly an issue, and could be observed also in orginal MATLAB code.
![image](https://user-images.githubusercontent.com/58003896/127736597-f4951017-cfde-4d11-aa8d-9ee17052680d.png)

The problem here are the input parameters, namely the dispersion characteristics.
The authors in their simulations used the global PCF dispersion characteristic and showed their results (plots for full dispersion dependency). They also provided (for others in order to reproduce the similar results) the terms of a corresponding Taylor series expansion truncated at *beta*<sub>10</sub>that yields near-identical results. They are **near-identical** but not the same ;-) Look at the remarks near the Table 1 in their work.
In our example we are using provided *beta*<sub>p</sub> coefficients, so naturally results are not identical.
Thanks for the remark and question.
Sylwia

**Comment by styojm** [comment]
Thanks Sylwia. Good to know that. I thought the difference would be less discernable but if their MATLAB code gives similar stuff then I won't worry about it. 

Regards
  Yujie
